"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-c(p@2i^cw=h_4^5ims5#gu%g=e!6t=$2!-pyr7ot_$7t$h!odz'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'accounts',
    'csp',  # Add accounts app for authentication
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'csp.middleware.CSPMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Configure login/logout redirect URLs
LOGIN_REDIRECT_URL = "/login/"
LOGOUT_REDIRECT_URL = "/login/"



# Custom user model


AUTH_USER_MODEL = 'bookshelf.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# SECURITY SETTINGS

# Disable debug mode in production
DEBUG = False

# Browser protections
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Secure cookies (sent only over HTTPS)
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True



# Content Security Policy

CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'",)
CSP_IMG_SRC = ("'self'", "data:")




# ------------------------------------------------------------
# HTTPS SECURITY CONFIGURATION
# These settings enforce secure HTTPS connections
# ------------------------------------------------------------

# Redirect all HTTP requests to HTTPS
# If a user visits http://example.com Django will redirect to https://example.com
SECURE_SSL_REDIRECT = True


# HTTP Strict Transport Security (HSTS)
# This tells browsers to ONLY communicate with the server using HTTPS
# The value is in seconds (31536000 seconds = 1 year)
SECURE_HSTS_SECONDS = 31536000


# Apply HSTS rule to all subdomains
# Example: api.example.com, blog.example.com
SECURE_HSTS_INCLUDE_SUBDOMAINS = True


# Allow your site to be included in browser HSTS preload lists
# This ensures browsers always force HTTPS even before visiting your site
SECURE_HSTS_PRELOAD = True



# ------------------------------------------------------------
# SECURE COOKIE SETTINGS
# Ensures cookies are only transmitted over HTTPS
# ------------------------------------------------------------

# Session cookies will only be sent over HTTPS
SESSION_COOKIE_SECURE = True

# CSRF cookies will only be sent over HTTPS
CSRF_COOKIE_SECURE = True


# ------------------------------------------------------------
# HTTP SECURITY HEADERS
# Protects against clickjacking, MIME sniffing and XSS
# ------------------------------------------------------------

# Prevent clickjacking attacks by disallowing site framing
X_FRAME_OPTIONS = "DENY"


# Prevent browsers from guessing content types
# This protects against malicious file execution
SECURE_CONTENT_TYPE_NOSNIFF = True


# Enable browser XSS protection
SECURE_BROWSER_XSS_FILTER = True